apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub-8d140
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-8d140
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters-sub-8d140
  project: ztp-app-project
  source:
    path: sno1/site-configs
    repoURL: https://github.com/yuchao4x/ZTP220.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
