---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ArgoCD
    patch: |-
      - op: replace
        path: /spec/repo/initContainers/0/image
        value: quay.io/openshift-kni/ztp-site-generator:4.10.0
