---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controller.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: pws-registry.intel.lab:5000/bitnami/sealed-secrets-controller:v0.19.4
