---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: disconnected-img4.12.19-x86-64-appsub
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  releaseImage: pws-registry.intel.lab:5000/openshift-release-dev/ocp-release:4.12.19-x86_64
