---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../gitops-catalog/advanced-cluster-management/operator/overlays/release-2.6
  - ../../gitops-catalog/advanced-cluster-management/instance/base
