---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno-ztp-intel-lab"
  # ① Change <ns> to the namespace in the namespace.yaml file in the previous step, for example: yourname-sno1
  namespace: "8d140-sno1"
spec:
  baseDomain: "intel.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  # ② Set the cluster version of the SNO you want to deploy, 
  # Note: Here the default is set to version 4.12.19 (If you set another version in step 3, here you can change 4.12.19 to the version number you set.)
  clusterImageSetNameRef: "disconnected-img4.12.19-x86-64-appsub"
  # ③ Add the public SSH key from Hub Cluster so that you can log in to the SNO cluster after installation from it,you can also use the public key of other nodes, which node's public key is used is the one used to ssh to the SNO nod. For example: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaMgir1TXoU0BpdhA1O6AvOmWvQbsHfBapjCS5fdBfOfVrgNe1+9ORDCsU7UKlU8kXUom3ToKb4kEO7qLoq2kWG3dlHomHnEr8mI3KKv+CySkkTxkZoJnBK1lyrmyL/U/G3q/rJr1/TjIXl3HKaZ2cd5dwdN/XD3qvknTyQv6Y9rQKOj8xHmiSI4sbk9EdCzv/yLcvXZWg6hwS/cchmmyn7w6YW0ggULHymq4vcSH5tQx5jcYdO9Vb2A0rXcGxFT8WLPIii5WgoSoTNoMev8ezoPkTTnWVx4lL6+zis0S4Kayyb1Km8i14W8+uhGHFuTvsz3nymo1aWzS7kZhQi8Ei9LeLJVuMbpcl5iyIvCTA1kj6sMCPe0YRhyMUBSvLcyLCavqKD3GTpeJQ46K1Q18KRzblXfSsDCn/pbdMLQeftf72mE394iE4GnHCcpKWEa6FJRr+4uiUs72wiyyJePISvcd+7N3t7rWShOqss4nWf4lGE2R39CuX3NSBvkVNn/E= root@localhost
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbiqpxeBPrI1eAMBG1bqUIbwAfNFVyw10KkUZhfXBljaxWp8gZcoGhrYqhyLHkLFHoT8q6kCLXKi46tbSXmXy+Eftotj99ShIBnh/tjnPNfpyQgLBkfgg/L6nT2TA/Gd+w59BzAjmfDSKD5+e/hL3nmcKW5UR6QTFz8TS5wRPPCeE/D6m/L5l5394Li9psdNDk+WYwbgtc4kXwsk9XOguvzN1T8ulvNdJ8Mc1zbJeYKphcu8VVOI3mVu3ds1ZZyJ5jqqi6L8lfe2aPnFs/KI+OHy7MJ01pyYk9A9FKkPd6JVq7X0+znAlq0I+UxRURfmNVjH8CrRk5OplLSZBx5Rt4wubA1B8UNpq+7pOTPxkxLjJOmsPXxWMX0Q6lg8WolOzk/tE/DcLM3sb2092Kzp/8KrCQcA81w3a6WwuktdIaWzrmz3/qzaerhCBF5BTlIwtfuCnRn/6gfk0VgSOBmW1XEDO0yoPFXxJlEwlvRoUWoJ9j8dUslepcF9GSvun/His= root@8d75-hubcluster"
  clusters:
    # ④ Here the clusterName must be set to the namespace in the namespace.yaml file in the previous step, for example: yourname-sno1
  - clusterName: "8d140-sno1"
    networkType: "OVNKubernetes"
    extraManifestPath: extra-manifest-self
    clusterLabels:
      common: true
      group-smcix12: ""
      # ⑤ Set a sites label for the cluster, change <ns> to the namespace in the namespace.yaml file in the previous step, for example: yourname-sno1
      sites: "8d140-sno1-intel-lab"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
        # ⑥ Fill in the intranet segment of your SNO cluster.
        # Note: Modify <SNO-server-NIC2-CIDR>, e.g. 192.168.8.0/24
      - cidr: 192.168.8.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
        # ⑦ Fill in the intranet ip of the hub node.
      - 192.168.8.75
    nodes:
        # ⑧ Set the host name of the SNO node, e.g. wse-yourname-sno.
        # Note: modify <hostName>, a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
      - hostName: "wse-8d140-sno"
        role: "master"
        # ⑨ Set the bmc address of your SNO node and change <bmc-ip> to the ip of your node BMC.
        # Note: If your sno machine is a dell r750, you should use this link: "idrac-virtualmedia+https://<bmc-ip>/redfish/v1/Systems/System.Embedded.1"; if your sno machine is supermicro(The bmc for supermicro machines requires a license and a specific version of bmc.) or dell, you should use this link: "redfish-virtualmedia://<bmc-ip>/redfish/v1/Systems/1".
        bmcAddress: "idrac-virtualmedia+https://192.168.8.199/redfish/v1/Systems/System.Embedded.1"
        #bmcAddress: "redfish-virtualmedia://<bmc-ip>/redfish/v1/Systems/1"
        # ⑩ Set the secret name of the BMC of the SNO node, this name is consistent with the <secret-name> defined in hub-prereqs/bmh-secret.yaml.
        bmcCredentialsName:
          name: "dell-sno-intel-lab-bmc-secret"
        # ⑪ Change <bootMACAddress> to the mac of the NIC where the SNO node's cluster network is located.
        # Note: 
        # The MAC must be the MAC of the internal NIC and is used as the cluster network.
        # If your SNO server does not have a system, you can find the MAC address through the BMC web page.
        # If your SNO server has a system and can ssh login, you can ssh login and use `ip a` command to find.
        bootMACAddress: "ec:2a:72:33:2a:8d"
        bootMode: "UEFI"
        rootDeviceHints:
          # ⑫ Set the path to the installation disk drive, for example, by name: /dev/sda to use the first disk named with /dev/sda. Or by uuid: /dev/disk/by-id/wwn-64cd98f04fde100024684cf3034da5c2 if your SNO server has a system and can ssh login, you can ssh login and use `ls /dev/disk/by-id/wwn-*` command to find.
          # Note: If you use the by-id method, here you need to set it to this form: wwn: "64cd98f04fde100024684cf3034da5c2"
          deviceName: "/dev/sda"
        # ⑬ The cpuset variable is used to isolate CPU cores and use the isolated cpu cores for the ocp cluster workload. Note: modify <cpuset>, how to set this variable, you can refer to Appendix “Set the cpuset variable”.
        cpuset: "0-1,64-65"
        # Set up the network of your SNO node
        nodeNetwork:
          interfaces:
            - name: eno2
              # ⑮ Fill in the MAC address of the internal network card in the SNO server. It is the same as the "⑪ bootMACAddress" variable.
              # Note: modify <SNO-server-NIC2-MAC>
              macAddress: "ec:2a:72:33:2a:8d"
          config:
            interfaces:
            - name: eno2
              type: ethernet
              state: up              
              ipv4:
                address:
                # ⑱ Set <SNO-server-NIC2-IP> to the ip, fill in the IP address of the internal network card in the SNO node.
                  # Note: modify <SNO-server-NIC2-IP>, e.g. 192.168.8.101
                - ip: 192.168.8.140
                  # ⑲ Set <SNO-server-NIC2-prefix-length> to the prefix-length of your <SNO-server-NIC2>'s network, for example: 24
                  prefix-length: 24
                enabled: true
                dhcp: false
            dns-resolver:
              config:
                server:
                    # ⑳ Set <Hub-Cluster-server-NIC2-IP> to the ip of your hub cluster physical machine, for example: 192.168.8.100
                  - 192.168.8.75
            routes:  # The default route here should be set to the NIC that can access the internet.
              config:
              - destination: 0.0.0.0/0
                # ㉑ Set <SNO-server-NIC2-GW> as the gateway of the NIC, you can get the gateway with the `ip r` command, for example: 192.168.8.8
                next-hop-address: 192.168.8.8
                next-hop-interface: eno2
